---
- name: Install git using Ansible
  hosts: all
  become: yes
  tasks:
    - name: Install git package
      dnf:
        name: git
        state: present




# This playbook installs git using ansible

